In [7]:
import pandas as pd
import numpy as np
import scipy.stats as st
import os

In [9]:
df = pd.read_csv('data_iris.csv' , header='infer')

In [10]:
df.shape

(150, 5)

In [11]:
df.head(3)

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa

In [36]:
x = df['Petal.Length']
y = df['Sepal.Length']

In [37]:
#Pearson
np.round(st.pearsonr(x,y),3)

array([0.872, 0.   ])

In [39]:
x.corr(y)

0.8717537758865831

In [53]:
np.round(df.corr(),3)

ValueError: could not convert string to float: 'Jared Diamond'

In [42]:
#Spearman
np.round(st.spearmanr(x,y),3)

array([0.882, 0.   ])

In [44]:
#Kendall
np.round(st.kendalltau(x,y),3)

array([0.719, 0.   ])

In [46]:
df = pd.read_csv('data_studentlist.csv',header = 'infer')

In [47]:
df.head(3)

name gender  age  grade absence bloodtype  height  weight
0   Jared Diamond      M   23      3       Y         O   165.3    68.2
1  Sarah O'Donnel      F   22      2       N        AB   170.1    53.0
2    Brian Martin      M   24      4       N         B   175.0    80.1

In [48]:
x = df.height
y = df.weight

In [49]:
n = len(x)
r = x.corr(y)
z = np.arctanh(r)
std_error_z = 1/np.sqrt(n-3)

In [52]:
{'low':np.tanh(z-st.norm.ppf(0.995)*std_error_z) , 'high':np.tanh(z+st.norm.ppf(0.995)*std_error_z)}

{'low': 0.11137578298592947, 'high': 0.9030812794020874}